Fixes
ilb/autocatalogs pull request #37
Opened 2023-06-28 13:42 UTC by dmitryi698

2023-07-03 05:44 UTC, MaximumQuiet requested changes

2023-07-03 05:44 UTC, MaximumQuiet commented on docs/technicalDocs/architecture.puml
> +System(service6, "service6", "service6")
А что это за сервисы?

2023-07-03 05:44 UTC, MaximumQuiet commented on prisma/schema.prisma
> +  url      = env("apps.autocatalogs.db")
так не пройдёт, в переменную apps.autocatalogs.db закидывается ссылка без логина и пароля

2023-07-03 05:44 UTC, MaximumQuiet commented on test/api/GetBodies.test.js
> +  // // console.log(result);
почему тесты закомменчены?

2023-07-18 06:28 UTC, dmitryi698 commented on test/api/GetBodies.test.js
> +  // // console.log(result);
отдельная ветка под тесты как закончу выложу

2023-07-18 11:48 UTC, merged